from typing import Literal, TypedDict, Optional, Dict
from datetime import datetime


# Für RemoteTableStatistics
StatisticsType = Literal["RECORD_COUNT", "SIMPLE", "HISTOGRAM"]
StatisticsInformationDict = TypedDict("StatisticsInformationDict", {
    "statisticsSupported": bool,
    "statisticsLimitedToRecordCount": bool,
    "statisticsType": Optional[StatisticsType],
    "businessName": str,
    "statisticsLatestUpdate": Optional[datetime]
})
StatisticsDict = Dict[str, StatisticsInformationDict]

# Für Views (Stand 10.07.2025)
ViewDetailsDict = TypedDict("ViewDetailsDict", {
    "@com.sap.vocabularies.Search.v1.Ranking": int | float,
    "@com.sap.vocabularies.Search.v1.WhyFound": dict,
    "@odata.context": str,
    "business_name": str,
    "business_purpose_purpose": None,
    "business_type": str,
    "business_type_description": str,
    "business_type_icon": str,
    "capabilities_list": None,
    "changed_by_user_name": Optional[str],
    "creation_date": str,
    "creator_user_name": Optional[str],
    "decommissioning_date": None,
    "deployment_date": Optional[str],
    "deployment_folder_id": None,
    "deployment_folder_id_ext": None,
    "deployment_folder_name": None,
    "deployment_name": None,
    "deployment_status": str,
    "deployment_status_description": str,
    "deployment_status_icon": str,
    "deprecation_date": None,
    "description": None,
    "exposed_for_consumption": str,
    "exposed_for_consumption_id": str,
    "favorites_user_id": None,
    "folder_icon": Optional[str],
    "folder_id": Optional[str],
    "folder_id_ext": Optional[str],
    "folder_name": Optional[str],
    "id": str,
    "is_shared": Optional[str],
    "is_shared_tag": Optional[str],
    "kind": str,
    "last_accessed": Optional[str],
    "last_accessed_globally": Optional[str],
    "modification_date": str,
    "name": str,
    "object_status": str,
    "object_status_description": str,
    "object_status_icon": str,
    "release_date": Optional[str],
    "release_state": str,
    "release_state_description": str,
    "release_state_icon": str,
    "remote_connection": None,
    "remote_connection_type": None,
    "remote_connection_type_description": None,
    "remote_entity": None,
    "repository_package": Optional[str],
    "repository_package_name": Optional[str],
    "space_description": str,
    "space_id": str,
    "space_name": str,
    "space_permission_user_is_member_in_source_space_id": str,
    "space_type": None,
    "technical_type": str,
    "technical_type_description": str,
    "technical_type_icon": str,
    "user_is_member_in_source_space_id": str,
    "business_purpose_description@com.sap.vocabularies.Search.v1.Snippets": Optional[str],
    "@com.sap.vocabularies.Search.v1.ParentHierarchies": list[dict],
})

# Für Analytische Modelle (Stand 13.07.2025)
AnalyticalModelsDetailsDict = TypedDict("AnalyticalModelsDetailsDict", {
    "@com.sap.vocabularies.Search.v1.Ranking": int | float,
    "@com.sap.vocabularies.Search.v1.WhyFound": dict,
    "@odata.context": str,
    "business_name": str,
    "business_purpose_purpose": None,
    "business_type": str,
    "business_type_description": str,
    "business_type_icon": str,
    "capabilities_list": None,
    "changed_by_user_name": Optional[str],
    "creation_date": str,
    "creator_user_name": Optional[str],
    "decommissioning_date": None,
    "deployment_date": Optional[str],
    "deployment_folder_id": None,
    "deployment_folder_id_ext": None,
    "deployment_folder_name": None,
    "deployment_name": None,
    "deployment_status": str,
    "deployment_status_description": str,
    "deployment_status_icon": str,
    "deprecation_date": None,
    "description": None,
    "exposed_for_consumption": str,
    "exposed_for_consumption_id": str,
    "favorites_user_id": None,
    "folder_icon": Optional[str],
    "folder_id": Optional[str],
    "folder_id_ext": Optional[str],
    "folder_name": Optional[str],
    "id": str,
    "is_shared": None,
    "is_shared_tag": None,
    "kind": str,
    "last_accessed": Optional[str],
    "last_accessed_globally": Optional[str],
    "modification_date": str,
    "name": str,
    "object_status": str,
    "object_status_description": str,
    "object_status_icon": str,
    "release_date": None,
    "release_state": None,
    "release_state_description": None,
    "release_state_icon": None,
    "remote_connection": None,
    "remote_connection_type": None,
    "remote_connection_type_description": None,
    "remote_entity": None,
    "repository_package": None,
    "repository_package_name": None,
    "space_description": str,
    "space_id": str,
    "space_name": str,
    "space_permission_user_is_member_in_source_space_id": str,
    "space_type": None,
    "technical_type": str,
    "technical_type_description": str,
    "technical_type_icon": str,
    "user_is_member_in_source_space_id": str,
    "business_purpose_entHierarchies": list[dict]
})
